apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons-kustomize
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:

          - clusters: {} # Read cluster secret from argo to generate som keys, like name=<clusterName>
          - git:
              repoURL: https://github.com/polaris-media/argocd-k8s-demo.git
              revision: HEAD
              directories:
              - path: src/addons/kustomize/clusters/{{.name}}/*
  template:
    metadata:
      name: 'kustomize-{{.path.basename}}'
    spec:
      project: devops
      source:
        repoURL: https://github.com/polaris-media/argocd-k8s-demo.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
