apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

resources:
  - ../../../base/pkl-demo

patches:
  - target:
      kind: Application
      name: pkl-k8s-demo
    patch: |-
      - op: replace
        path: /spec/source/directory/include
        value: applicationset_prod.yaml
        
